# Generated by Django 4.0.2 on 2022-08-27 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('city_image', models.ImageField(upload_to='city_images')),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_ds', models.TextField(max_length=100)),
                ('hotel_image', models.ImageField(upload_to='')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_name', to='travel.city')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_ds', models.TextField(max_length=100)),
                ('room_image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(max_length=10)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_name', to='travel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_ds', models.TextField()),
                ('place_image', models.ImageField(upload_to='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place', to='travel.city')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Date')),
                ('check_out', models.DateField(verbose_name='Date')),
                ('members', models.IntegerField(max_length=20)),
                ('total_rooms', models.IntegerField(max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book', to='travel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
