# Generated by Django 4.0.2 on 2022-08-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='places',
            name='place',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotelbooking', to='travel.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='city', to='travel.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='city_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_of_city', to='travel.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='place_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_name', to='travel.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='members',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_ds',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_ds',
            field=models.TextField(),
        ),
    ]
