# Generated by Django 3.2.6 on 2022-08-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_rename_city_name_city_name_remove_booking_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=150)),
                ('res_ds', models.TextField()),
                ('res_image', models.ImageField(upload_to='')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_city', to='travel.city')),
            ],
        ),
    ]
