# Generated by Django 3.2.6 on 2022-08-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_restaurant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('confirmpassword', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='city_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
    ]
