# Generated by Django 3.2.6 on 2022-09-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_registration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='image',
        ),
    ]
