# Generated by Django 4.0.2 on 2022-09-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_remove_registration_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=150)),
                ('pack_des', models.TextField()),
                ('room_image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Package_name', to='travel.hotel')),
            ],
        ),
    ]
