# Generated by Django 4.0.2 on 2022-09-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_room_packages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room_packages',
            new_name='packages',
        ),
    ]
