# Generated by Django 4.0.2 on 2022-09-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_rename_room_packages_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='room_image',
        ),
    ]
