# Generated by Django 4.0.2 on 2022-09-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_packages_room_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='packages',
            new_name='package',
        ),
    ]
