# Generated by Django 4.0.2 on 2022-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_rename_packages_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='exit', upload_to=''),
            preserve_default=False,
        ),
    ]
