# Generated by Django 3.2.6 on 2022-09-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20220902_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='roombooking', to='travel.room'),
            preserve_default=False,
        ),
    ]
