# Generated by Django 3.2.6 on 2022-09-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_booking_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room_name',
        ),
    ]
