# Generated by Django 3.2.6 on 2022-09-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_rename_name_room_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_name',
        ),
    ]
