# Generated by Django 3.2.3 on 2022-09-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_booking_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gender',
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicles',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
