# Generated by Django 4.0.2 on 2022-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_auto_20220907_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('cus_name', models.CharField(max_length=50)),
            ],
        ),
    ]
