# Generated by Django 4.0.2 on 2022-09-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vehicles',
        ),
    ]
