# Generated by Django 4.1.1 on 2022-09-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_remove_booking_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='password',
            field=models.CharField(default=12345, max_length=200),
            preserve_default=False,
        ),
    ]
