# Generated by Django 4.1.1 on 2022-09-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_hotel_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_ds',
            new_name='hotel_description',
        ),
    ]
