# Generated by Django 4.1.1 on 2022-10-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_rename_hotel_ds_hotel_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image',
            field=models.FileField(blank=True, null=True, upload_to='hotles'),
        ),
    ]
