# Generated by Django 4.1.1 on 2022-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_alter_hotel_hotel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_ds',
            new_name='room_description',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image',
            field=models.FileField(blank=True, null=True, upload_to='hotels'),
        ),
    ]
