# Generated by Django 4.1.1 on 2022-10-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_rename_room_ds_room_room_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='pack_des',
            new_name='package_description',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='pack_name',
            new_name='package_name',
        ),
    ]
