# Generated by Django 4.0.2 on 2022-10-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_rename_pack_des_package_package_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vechile',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
