# Generated by Django 3.2.6 on 2023-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_booking_vechile'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_map',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
