# Generated by Django 3.2.6 on 2023-01-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_places_place_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='place_map',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='res_map',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
