# Generated by Django 3.2.6 on 2023-01-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_auto_20230102_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='fam_map',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
