# Generated by Django 3.2.6 on 2023-01-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_places_fam_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='fam_map',
        ),
    ]
