# Generated by Django 3.2.6 on 2023-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_remove_places_fam_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='fam_map',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
